- name: Touch file
  hosts: localhost
  connection: local
  tasks:
    - name: Ensure file exists at /var/lib/postgresql
      ansible.builtin.file:
        path: /var/lib/postgresql/test.txt
        state: touch
        mode: '0644'   

    #- name: Ensure psycopg2-binary is installed
    #  ansible.builtin.pip:
    #    name: psycopg2-binary
    #    state: present   

    #- name: Create users table
    #  community.postgresql.postgresql_table:
    #    login_host: 127.0.0.1
    #    login_port: 5433
    #    login_user: postgres
    #    login_password: postgres
    #    db: postgres
    #    name: users
    #    columns:
    #      - id serial PRIMARY KEY
    #      - username varchar(50) NOT NULL
    #      - email varchar(100)
    #      - created_at timestamp DEFAULT CURRENT_TIMESTAMP
    #    state: present
